name: Health Check

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check health
        uses: jtalk/url-health-check-action@v2
        with:
          url: ${{ secrets.HEROKU_HEALTH_CHECK_URL }}
          max-attempts: 3 # Optional, defaults to 1
          retry-delay: 5s # Optional, only applicable to max-attempts > 1
